package net.hetic.findamovie.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import net.hetic.findamovie.model.Movie;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MOVIE.
*/
public class MovieDao extends AbstractDao<Movie, Long> {

    public static final String TABLENAME = "MOVIE";

    /**
     * Properties of entity Movie.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Adult = new Property(0, Boolean.class, "adult", false, "ADULT");
        public final static Property Id = new Property(1, Long.class, "id", true, "_id");
        public final static Property Overview = new Property(2, String.class, "overview", false, "OVERVIEW");
        public final static Property Original_title = new Property(3, String.class, "original_title", false, "ORIGINAL_TITLE");
        public final static Property Release_date = new Property(4, String.class, "release_date", false, "RELEASE_DATE");
        public final static Property Poster_path = new Property(5, String.class, "poster_path", false, "POSTER_PATH");
        public final static Property Popularity = new Property(6, Double.class, "popularity", false, "POPULARITY");
        public final static Property Title = new Property(7, String.class, "title", false, "TITLE");
        public final static Property Vote_average = new Property(8, Double.class, "vote_average", false, "VOTE_AVERAGE");
        public final static Property Vote_count = new Property(9, Integer.class, "vote_count", false, "VOTE_COUNT");
    };


    public MovieDao(DaoConfig config) {
        super(config);
    }
    
    public MovieDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MOVIE' (" + //
                "'ADULT' INTEGER," + // 0: adult
                "'_id' INTEGER PRIMARY KEY ," + // 1: id
                "'OVERVIEW' TEXT," + // 2: overview
                "'ORIGINAL_TITLE' TEXT," + // 3: original_title
                "'RELEASE_DATE' TEXT," + // 4: release_date
                "'POSTER_PATH' TEXT," + // 5: poster_path
                "'POPULARITY' REAL," + // 6: popularity
                "'TITLE' TEXT," + // 7: title
                "'VOTE_AVERAGE' REAL," + // 8: vote_average
                "'VOTE_COUNT' INTEGER);"); // 9: vote_count
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MOVIE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Movie entity) {
        stmt.clearBindings();
 
        Boolean adult = entity.getAdult();
        if (adult != null) {
            stmt.bindLong(1, adult ? 1l: 0l);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String overview = entity.getOverview();
        if (overview != null) {
            stmt.bindString(3, overview);
        }
 
        String original_title = entity.getOriginal_title();
        if (original_title != null) {
            stmt.bindString(4, original_title);
        }
 
        String release_date = entity.getRelease_date();
        if (release_date != null) {
            stmt.bindString(5, release_date);
        }
 
        String poster_path = entity.getPoster_path();
        if (poster_path != null) {
            stmt.bindString(6, poster_path);
        }
 
        Double popularity = entity.getPopularity();
        if (popularity != null) {
            stmt.bindDouble(7, popularity);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
 
        Double vote_average = entity.getVote_average();
        if (vote_average != null) {
            stmt.bindDouble(9, vote_average);
        }
 
        Integer vote_count = entity.getVote_count();
        if (vote_count != null) {
            stmt.bindLong(10, vote_count);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public Movie readEntity(Cursor cursor, int offset) {
        Movie entity = new Movie( //
            cursor.isNull(offset + 0) ? null : cursor.getShort(offset + 0) != 0, // adult
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // overview
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // original_title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // release_date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // poster_path
            cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6), // popularity
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // title
            cursor.isNull(offset + 8) ? null : cursor.getDouble(offset + 8), // vote_average
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9) // vote_count
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Movie entity, int offset) {
        entity.setAdult(cursor.isNull(offset + 0) ? null : cursor.getShort(offset + 0) != 0);
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setOverview(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOriginal_title(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRelease_date(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPoster_path(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPopularity(cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6));
        entity.setTitle(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setVote_average(cursor.isNull(offset + 8) ? null : cursor.getDouble(offset + 8));
        entity.setVote_count(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Movie entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Movie entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
