package net.hetic.findamovie.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table MOVIE.
 */
public class Movie implements Parcelable {

    private Boolean adult;
    private Long id;
    private String overview;
    private String original_title;
    private String release_date;
    private String poster_path;
    private Double popularity;
    private String title;
    private Double vote_average;
    private Integer vote_count;

    public Movie() {
    }

    public Movie(Long id) {
        this.id = id;
    }

    public Movie(Boolean adult, Long id, String overview, String original_title, String release_date, String poster_path, Double popularity, String title, Double vote_average, Integer vote_count) {
        this.adult = adult;
        this.id = id;
        this.overview = overview;
        this.original_title = original_title;
        this.release_date = release_date;
        this.poster_path = poster_path;
        this.popularity = popularity;
        this.title = title;
        this.vote_average = vote_average;
        this.vote_count = vote_count;
    }

    public Boolean getAdult() {
        return adult;
    }

    public void setAdult(Boolean adult) {
        this.adult = adult;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOverview() {
        return overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }

    public String getOriginal_title() {
        return original_title;
    }

    public void setOriginal_title(String original_title) {
        this.original_title = original_title;
    }

    public String getRelease_date() {
        return release_date;
    }

    public void setRelease_date(String release_date) {
        this.release_date = release_date;
    }

    public String getPoster_path() {
        return poster_path;
    }

    public void setPoster_path(String poster_path) {
        this.poster_path = poster_path;
    }

    public Double getPopularity() {
        return popularity;
    }

    public void setPopularity(Double popularity) {
        this.popularity = popularity;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Double getVote_average() {
        return vote_average;
    }

    public void setVote_average(Double vote_average) {
        this.vote_average = vote_average;
    }

    public Integer getVote_count() {
        return vote_count;
    }

    public void setVote_count(Integer vote_count) {
        this.vote_count = vote_count;
    }


    /**
     * Parcelable methods
     */

    @Override
    public int describeContents() {
        return title.hashCode()+vote_average.hashCode();
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(id);
        dest.writeString(overview);
        dest.writeString(original_title);
        dest.writeString(release_date);
        dest.writeString(poster_path);
        dest.writeDouble(popularity);
        dest.writeString(title);
        dest.writeDouble(vote_average);
        dest.writeInt(vote_count);
    }

    public static final Creator<Movie> CREATOR
            = new Creator<Movie>() {
        @Override
        public Movie createFromParcel(Parcel source) {
            return new Movie(source);
        }

        @Override
        public Movie[] newArray(int size) {
            return new Movie[size];
        }
    };

    private Movie(Parcel source){
        adult = false;
        id = source.readLong();
        overview = source.readString();
        original_title = source.readString();
        release_date = source.readString();
        poster_path = source.readString();
        popularity = source.readDouble();
        title = source.readString();
        vote_average = source.readDouble();
        vote_count = source.readInt();
    }
}
